# Beam properties
beam_runner: DataflowRunner
beam_streaming: False

# Dataflow properties
dataflow_job_name: laminar-batch-development
dataflow_project_id: logee-data-dev
dataflow_region: asia-southeast2
dataflow_temp_location: gs://laminar-development/batch/temp/
dataflow_staging_location: gs://laminar-development/batch/staging/
dataflow_subnetwork: https://www.googleapis.com/compute/v1/projects/logee-data-dev/regions/asia-southeast2/subnetworks/logee-subnet-general-2-development
dataflow_no_use_public_ips: True
dataflow_save_main_session: True
dataflow_machine_type: n1-standard-1
dataflow_max_num_workers: 2
dataflow_autoscaling_algorithm: THROUGHPUT_BASED
dataflow_labels:
  project: laminar
  env: development
dataflow_drain_wait_check_interval_seconds: 10.0
dataflow_drain_wait_max_seconds: 1800.0
dataflow_drain_wait_max_threads: 2
dataflow_running_wait_check_interval_seconds: 5.0
dataflow_running_wait_max_seconds: 1800.0
dataflow_running_wait_max_threads: 2
dataflow_service_account: laminar-general@logee-data-dev.iam.gserviceaccount.com
dataflow_enable_streaming_engine: False
dataflow_experiments: use_runner_v2

# BigQuery Raw Datalake properties
bigquery_raw_project_id: logee-data-dev
bigquery_raw_dataset: raw_datalake

# BigQuery L1 properties
bigquery_l1_project_id: logee-data-dev
bigquery_l1_schema_bucket: logee-schema-development
bigquery_l1_schema_folder: schema/L1/datalake
bigquery_l1_dead_letter_dataset: dead_letter
bigquery_l1_dead_letter_failures_table: raw_to_l1_failures
bigquery_l1_dead_letter_unconfigured_table: raw_to_l1_unconfigured